version: "3.5"
services:
  webpacker:
    build: .
    env_file:
      - ./.env
    command: ./bin/webpack-dev-server
    volumes:
      - .:/app
      - bundle:/bundle
    ports:
      - '3035:3035'
  web:
    build: .
    command: ./config/docker/start.sh
    volumes:
      - .:/app
      - bundle:/bundle
      - $SSH_AUTH_SOCK:/ssh-agent
      - ~/.ssh/known_hosts:/etc/ssh/ssh_known_hosts
    ports:
      - "3000:3000"
    env_file:
      - ./.env

volumes:
  pgdata:
    driver: local
  bundle:
    driver: local
